#!/usr/bin/env tsx
// scripts/hubspot-bootstrap.ts
//
// Creates 5 custom Contact properties in HubSpot that the site uses when
// syncing leads. Run once before going live:
//
//   npm run hubspot:bootstrap
//
// Idempotent — a 409 Conflict response means the property already exists
// and is silently skipped. Safe to run again at any time.

import "dotenv/config";

const TOKEN  = process.env.HUBSPOT_ACCESS_TOKEN ?? "";
const PORTAL = process.env.HUBSPOT_PORTAL_ID   ?? "";

if (!TOKEN || TOKEN.startsWith("REPLACE")) {
  console.error(
    "\n❌  HUBSPOT_ACCESS_TOKEN is not set in .env.local\n" +
    "    Set it to your pat-na2-... token and re-run.\n",
  );
  process.exit(1);
}

const BASE = "https://api.hubapi.com";

// ── Property definitions ─────────────────────────────────────────────────────

interface Option {
  label:        string;
  value:        string;
  displayOrder: number;
  hidden:       boolean;
}

interface PropertyDef {
  name:        string;
  label:       string;
  type:        "string" | "enumeration";
  fieldType:   "text" | "textarea" | "select";
  description: string;
  options?:    Option[];
}

const PROPERTIES: PropertyDef[] = [
  {
    name:        "lead_source_category",
    label:       "Lead Source Category",
    type:        "enumeration",
    fieldType:   "select",
    description: "Which Forge Point form or channel generated this contact",
    options: [
      { label: "BOV Popup",     value: "bov_popup",     displayOrder: 0, hidden: false },
      { label: "Contact Form",  value: "contact_form",  displayOrder: 1, hidden: false },
      { label: "Estimate Form", value: "estimate_form", displayOrder: 2, hidden: false },
    ],
  },
  {
    name:        "property_address",
    label:       "Property Address",
    type:        "string",
    fieldType:   "text",
    description: "Subject property address submitted by the lead",
  },
  {
    name:        "service_interest",
    label:       "Service Interest",
    type:        "string",
    fieldType:   "textarea",
    description: "Services the lead is interested in (may be comma-separated list)",
  },
  {
    name:        "urgency_level",
    label:       "Urgency Level",
    type:        "enumeration",
    fieldType:   "select",
    description: "Timeline urgency selected on the contact or estimate form",
    options: [
      { label: "Urgent (ASAP)",      value: "URGENT",   displayOrder: 0, hidden: false },
      { label: "Standard (2–3 wks)", value: "STANDARD", displayOrder: 1, hidden: false },
      { label: "Flexible",           value: "FLEXIBLE", displayOrder: 2, hidden: false },
    ],
  },
  {
    name:        "estimate_range",
    label:       "Estimate Range",
    type:        "string",
    fieldType:   "text",
    description: "Price range generated by the Forge Point online estimator (e.g. $1,500 – $2,800)",
  },
];

// ── Create one property ──────────────────────────────────────────────────────

async function createProperty(prop: PropertyDef): Promise<"created" | "exists" | "error"> {
  const body: Record<string, unknown> = {
    name:        prop.name,
    label:       prop.label,
    type:        prop.type,
    fieldType:   prop.fieldType,
    description: prop.description,
    groupName:   "contactinformation",
  };
  if (prop.options) body.options = prop.options;

  const res = await fetch(`${BASE}/crm/v3/properties/contacts`, {
    method:  "POST",
    headers: {
      Authorization:  `Bearer ${TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  if (res.status === 409) return "exists";   // property already present — OK

  if (!res.ok) {
    const txt = await res.text().catch(() => "(no body)");
    console.error(`  ❌  ${prop.name} — ${res.status}: ${txt}`);
    return "error";
  }

  return "created";
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log("\n── Forge Point HubSpot Bootstrap ──────────────────────────────");
  console.log(`   Portal : ${PORTAL || "(HUBSPOT_PORTAL_ID not set)"}`);
  console.log(`   Props  : ${PROPERTIES.length} custom Contact properties`);
  console.log("────────────────────────────────────────────────────────────────\n");

  let created = 0;
  let skipped = 0;
  let errors  = 0;

  for (const prop of PROPERTIES) {
    const result = await createProperty(prop);
    if (result === "created") {
      console.log(`  ✅  ${prop.name}`);
      created++;
    } else if (result === "exists") {
      console.log(`  ⚠️   ${prop.name} — already exists, skipped`);
      skipped++;
    } else {
      errors++;
    }
  }

  console.log(`\n  ${created} created · ${skipped} skipped · ${errors} errors`);

  if (errors === 0) {
    console.log(`\n  ✅  All properties confirmed.`);
    console.log(
      `  Verify at: https://app.hubspot.com/contacts/${PORTAL}/properties\n`,
    );
  } else {
    console.log(`\n  ⚠️  Some properties failed. Check token permissions.\n`);
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
